[build]
  command = "npm run build"
  publish = "public"

[context.production]
  environment = { NODE_ENV = "production" }

[build.environment]
  NODE_VERSION = "12"

[[headers]]
  for = "/*"
  [headers.values]
    Link = '''
    </main.css>; rel=preload; as=style, \
    </bundle.js>; rel=preload; as=script'''

[[redirects]]
  from = "https://dekoolecentrale.com/*"
  to = "https://dekoolecentrale.nl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.dekoolecentrale.com/*"
  to = "https://dekoolecentrale.nl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://koole.io/*"
  to = "https://dekoolecentrale.nl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.koole.io/*"
  to = "https://dekoolecentrale.nl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.dekoolecentrale.nl/*"
  to = "https://dekoolecentrale.nl/:splat"
  status = 301
  force = true